### ISSUE TITLE
3 - Installation Failed: Unable to Download Various Portions of Archives

### ISSUE THREAD

**Issue by ForgottenGlory** [ForgottenGlory/MOISE#10]
Is bug?: Confirm

Read the readme?: Confirm

List Version: Latest as of 3/31/2022

Reproducable?: Yes

Discord Username: Raptor005#3701

Rule 11?: No

Type: MOISE Installation via Wabbajack

Summary: Installation Failed: Unable to Download Various Portions of Archives

Details: 

Steps to reproduce: Occurs consistently, even with clean re-installs of base game and Wabbajack. Other games / modlists via Wabbajack work properly so this appears to be a MOISE specific issue. Thank you for reviewing.

Crash log: https://drive.google.com/file/d/1PiO6XDMzNheDtD4j1g01deSFr0tI2I9f/view?usp=sharing

Screenshots: https://drive.google.com/file/d/1xtfty8689Iha4X3uWp3Oz7ddkVGn4E2e/view?usp=sharing

**Comment by LordBladesman** [comment]
Dose this in include Morrowind.ini ??  I am using the GOG Version, it will not hash.

Crash log  : https://pastebin.com/z3iMR9ap via @pastebin
