### ISSUE TITLE
Broken Link: Cliffracer Replacer-43925-0-9.7z

### ISSUE THREAD

**Issue by Jared-woodruff** [ForgottenGlory/MOISE#4]
Hi ForgottenGlory,

Love the mod list, missing one file which was hidden on the Nexus recently. 
[Cliffracer Replacer-43925-0-9.7z ](https://www.nexusmods.com/morrowind/mods/43925)
has been replaced by:
[Cliff Racer Replacer 2.0](https://www.nexusmods.com/morrowind/mods/48978)

Cheers

**Comment by MelvinMarvin** [comment]
Does anyone know how to fix this, or are we gonna have to wait for them to?

**Comment by ForgottenGlory** [comment]
Fixed in v1.2.3
