### ISSUE TITLE
Broken downloads for Psy_VGRCreatureEdition_1_2.7z and Psy_Azura_Replacer1.7z

### ISSUE THREAD

**Issue by ChunkeeMunkee** [ForgottenGlory/MOISE#7]
The automated downloads for the above two files appear to be failing following the list update.

This was an issue with the previous version of the list as well - the below links are currently working for manual downloads:

Psy_VGRCreatureEdition_1_2.7z
https://www.moddb.com/games/morrowind/addons/vivec-god-replacer

Psy_Azura_Replacer1.7z
https://www.moddb.com/addons/azura-replacer

**Comment by dedolence** [comment]
Thank you for this!
